BNC/BNC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls'))
]

BNC/index/urls.py
from django.urls import pathfrom .import viewsfrom django.views.generic.detail import DetailViewfrom django.views.generic import ListViewfrom .models import Expert, Reviewurlpatterns = [    path('', ListView.as_view(queryset = Review.objects.all(), template_name='index/index.html'), name = 'expert'),    path('expert/<int:pk>', DetailView.as_view(model = Expert, template_name='index/detail.html')),    path('contacts/', views.contacts),    path('about/', views.about),    path('work/', views.work),    path('experts/', views.experts),    path('services/', views.services),    path('review/', views.review)]

BNC/index/models.py
from django.db import models

# Create your models here.
class Expert(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.CharField(max_length=10)
    image = models.ImageField(upload_to='static\images')
    def __str__(self):
        return self.name

class Review(models.Model):
    name = models.CharField(max_length=30)
    review = models.TextField()
    type = models.CharField(max_length=50)
    def __str__(self):
        return self.name

BNC/index/forms.py
from django.forms import ModelForm
from .models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

BNC/index/views.py
from django.shortcuts import render
from .forms import ReviewForm

# Create your views here.

def contacts(request):
    return render(request, 'index/contacts.html')

def about(request):
    return render(request, 'index/about.html')

def work(request):
    return render(request, 'index/work.html')

def experts(request):
    return render(request, 'index/experts.html')

def services(request):
    return render(request, 'index/services.html')

def review(request):
    form = ReviewForm()
    if request.method == 'POST':
        print(request.POST)
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
    context = {'form' : form}
    return render(request, 'index/review.html', context)

BNC/index/templates/index/about.html
{% extends 'index/template.html' %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <br><br>
            <h2 class="text-center">О компании</h2>
            <br><br>
            <p>
                В компании постоянно разрабатываются и совершенствуются методики проведения экспертиз. Многие сотрудники компании постоянно публикуются как в центральной прессе, так и в специализированной литературе.

Сотрудники компании постоянно стремятся к повышению своего профессионального уровня.

Бюро независимых судебных экспертиз - одна из наиболее динамично развивающихся компаний на своем рынке, ориентирующаяся на самые жесткие мировые стандарты и на самый высокой уровень предоставляемых услуг.

Сотрудники Бюро имеют все соответствующие сертификаты, дипломы, аттестаты и свидетельства на проведение судебных экспертиз. Бюро обладает необходимой материально-технической и лабораторной базой, что позволяет проводить экспертизы и исследования на самом высоком техническом и профессиональном уровне.

            </p>
            <p>
            ООО «Бюро независимых судебных экспертиз» - это динамично развивающаяся в Краснодарском крае компания, нацеленная на обеспечение прозрачности и законности современной системы судопроизводства в Российской Федерации. Основным принципом деятельности компании является соблюдение законности и всестороннее содействие правоохранительным и судебным органам нашего региона. Современные реалии арбитражного, гражданского и уголовного судопроизводства, ввиду большой загруженности государственных экспертных учреждений, диктуют свою необходимость в негосударственных экспертных организациях. ООО «БНЭС» осуществляет экспертную деятельность на основании ст. 41 федерального закона от 31.05.2001г. №73-ФЗ «О государственной судебно-экспертной деятельности в Российской Федерации», в своем штате имеет экспертов в прошлом осуществляющих свою деятельность в стенах государственных судебных лабораторий и муниципальных унитарных предприятий Краснодарского края. Сотрудники нашего Бюро также рады предложить Вам услуги по юридическому сопровождению, в качестве представителя в судебном процессе по гражданским, арбитражным и уголовным делам. Мы всегда рады видеть Вас в стенных нашего экспертного учреждения по вопросам консультирования и дальнейшей плодотворной работы.

        </p>
            <p><h5 class="text-right">С Уважением Руководитель Лазарев О.С.</h5></p>
        </div>
    </div>
</div>

{% endblock %}

BNC/index/templates/index/contacts.html
{% extends 'index/template.html' %}

{% load static %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <br><br>
            <h2 class="text-center">Контакты</h2>
            <br><br>
            <p>Наш адрес: 350018, г. Краснодар, ул. Сормовская, 7, бизнес-центр "Сормовка", оф.211/6</p>

                <p>Тел./факс: 8 (861) 267-89-96</p>

                <p>Моб. тел: 8 (918) 432-80-70</p>

                <p>Сайт: https://bnc-expert.ru</p>

                <p>Эл. почта: mail@bnc-expert.ru</p>

                <p>Instagram: https://www.instagram.com/bncexpert/</p>

                <p>Вконтакте: https://vk.com/club30748081</p>

        </div>
    </div>
</div>

{% endblock %}

BNC/index/templates/index/detail.html
{% extends 'index/template.html' %}

{% load static %}

{% block content %}

<br>

<div class="container" >
    <div class="row ">
        <div class="col-12">
            <h2 class="text-center">{{ expert.name }} экпертиза</h2>
            <h6>{{ expert.description }}</h6>
        </div>
    </div>
</div>



{% endblock %}

BNC/index/templates/index/experts.html
{% extends 'index/template.html' %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <br><br>
            <h2 class="text-center">Эксперты</h2>
            <br><br>
            <h2 class="text-center">Лазарев Олег Сергеевич</h2>
            <p><h5 class="text-center">Эксперт-строитель</h5></p>

           <p>Базовое образование – инженер-строитель по специальности «Городское строительство и хозяйство».</p>

            <p>Диплом о высшем образовании Кубанского Государственного Технологического Университета серии ВСВ 1468419 №822111, 30.05.2005 г. Краснодар 2005 г.</p>

            <p>Дополнительное обучение – прошел проверку знаний сейсмостойкого строительства СНиП II-7-81* «Строительство в сейсмических районах».</p>

            <p>Общий стаж работы по специальности - 16 лет.</p>

            <p>Квалификационный аттестат кадастрового инженера №23-11-845. Стаж экспертной работы по специальности 16.1
            «Исследование строительных объектов и территории, функционально связанной с ними, в том числе с целью проведения их оценки» по классификации СЭУ Министерства юстиции РФ с 2007 года.</p>


            <br><br><br><br>
            <h2 class="text-center">Попов Александр Владимирович</h2>
            <p><h5 class="text-center">Эксперт-товаровед</h5></p>

            <p>Имеет высшее инженерно-техническое образование, специальную подготовку по специальности 25.1
            «Исследование радиоэлектронных, электротехнических и электромеханических устройств бытового назначения», стаж работы по специальности – с 2012 г.</p>


            <br><br><br><br>
            <h2 class="text-center">Борисевич Андрей Витальевич</h2>

            <p><h5 class="text-center">Эксперт-оценщик</h5></p>

            <p>Образование: Диплом по программе «Оценка собственности», выданный Ставропольским финансово-экономическим институтом серия ИВС №0501323 от 04 июня 2003 года.
            Квалификация – оценщик Член Ассоциации «Межрегиональный союз оценщиков «МСО» (Свидетельство Ассоциации «Межрегиональный союз оценщиков «МСО», регистрационный № 0707 от 27.05.2010г.</p>

            <p>Стаж работы: общий стаж работы по специальности более 10 лет. Стаж экспертной работы по специальности по классификации СЭУ Министерства юстиции РФ с 2006 года.</p>


            <br><br><br><br>
            <h2 class="text-center">Макаренко Валерий Таварович</h2>

            <p><h5 class="text-center">Эксперт-почерковед, ТЭД</h5></p>

            <p>Образование: в 1992 году поступил в Высшую школу Министерства внутренних дел Республики Узбекистан и в 1997 году окончил полный курс Академии Министерства Министерства внутренних дел Республики Узбекистан по специальности «Правоведение».</p>

            <p>Дополнительное обучение: Прошёл Сертификацию в Российском Федеральном центре судебной экспертизы при Министерстве юстиции Российской Федерации в области «Исследование почерка и подписей».</p>

            <p>Стаж экспертной работы по специальности «Исследование почерка и подписей» по классификации СЭУ Министерства юстиции РФ более 20 лет.</p>


            <br><br><br><br>
            <h2 class="text-center">Яхонтов Сергей Алексеевич</h2>

            <p><h5 class="text-center">Эксперт-программист</h5></p>

            <p>Базовое образование – инженер по специальности «Программное обеспечение вычислительной техники и автоматизированных систем»,
                диплом о высшем образовании Кубанского Государственного Технологического Университета с отличием серии ИВС 0023358,
                регистрационный номер 74177 от 28.06.2002г. Общий стаж работы по специальности, включая экспертную деятельность более 15 лет.</p>


            <br><br><br><br>
            <h2 class="text-center">Барбаш Валерий Николаевич</h2>

            <p><h5 class="text-center">Эксперт-фоноскопист</h5></p>

            <p>
                Имеет высшее техническое образование (специальность по диплому «Радиофизика и электроника»),
                квалификацию судебного эксперта по специальности 7.2 «Исследование звуковой среды, условий, средств,
                материалов и следов звукозаписей», стаж экспертной деятельности – 12 лет.
            </p>
        </div>
    </div>
</div>

{% endblock %}

BNC/index/templates/index/index.html
{% extends 'index/template.html' %}

{% load static %}

{% block content %}

<style>
    #mainContent ul li {
      transition: all .5s ease-in-out;
      transform: translate3d(60px, 0, 0);
    }

    #mainContent ul li.active {
      transform: translate3d(0px, 0, 0);
    }
</style>

<!-- Карусель -->
<div id="carousel" class="carousel slide text-center" data-ride="carousel" >
  <div class="carousel-inner">
      <div class="carousel-item active">
          <a href="expert/1"> <img class="d-block w-100" src="{% static 'images/Stroitel-no-tehnicheskaya-e-kspertiza.jpg' %}" alt="Первый слайд" width="800" height="600"></a>
        <div class="carousel-caption d-none d-md-block">
          <h1 class="text-left">Строительно-техническая экспертиза</h1>
          <h2 class="text-left">От 5 000р</h2>
        </div>
      </div>
      <div class="carousel-item">
          <a href="expert/2"> <img class="d-block w-100" src="{% static 'images/unnamed_mYzuxqI.jpg' %}" alt="Второй слайд" width="800" height="600"></a>
          <div class="carousel-caption d-none d-md-block">
            <h1 class="text-left">Компьютерно-Техническая экспертиза</h1>
            <h2 class="text-left">От 5 000р</h2>
          </div>
      </div>
  </div>
  <a class="carousel-control-prev dark" href="#carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<p></p>
<!-- НЕЗАВИСИМАЯ СУДЕБНАЯ И ДОСУДЕБНАЯ ЭКСПЕРТИЗА В КРАСНОДАРЕ И КРАСНОДАРСКОМ КРАЕ -->
<br>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center animate__animated animate__fadeIn" >НЕЗАВИСИМАЯ СУДЕБНАЯ И ДОСУДЕБНАЯ ЭКСПЕРТИЗА В КРАСНОДАРЕ И КРАСНОДАРСКОМ КРАЕ</h2>
      <br>
      <div id="mainContent">
        <ul id="myList" type="None">
          <li><h5>Экспертиза в ООО "Бюро независимых судебных экспертиз" - это всегда качественно и быстро!</h5></li>
          <li><h5>ООО «Бюро независимых судебных экспертиз», создано с целью содействия судебным и правоохранительным</h5></li>
          <li><h5>органам, защиты прав и свобод граждан Российской Федерации, интересов государства и хозяйствующих</h5></li>
          <li><h5>субъектов посредством проведения объективных научно обоснованных внесудебных и судебных экспертных</h5></li>
          <li><h5>исследований.</h5></li>
          <br>
          <li><h5>Одним из основным видом деятельности экспертного Бюро является осуществление экспертных</h5></li>
          <li><h5>исследований: строительно-технических, землеустроительных, товароведческих, оценочных и</h5></li>
          <li><h5>почерковедческих экспертиз.</h5></li>
          <br>
          <hr>
        </ul>
        <h2 class="text-center">ОТЗЫВЫ</h2>
        <br>
      </div>
    </div>
  </div>
</div>

<!-- Отзывы -->
<div class="bg-dark">
  <br>
  <div class="container">
    <div class="row">
        {% for review in object_list reversed %}
          {% if forloop.counter <= 3 %}
            <div class="col-md-4">
              <div class="card">
                {% if review.type == 'Строительно-Техническая' %}
                <img src="{% static 'images/Stroitel-no-tehnicheskaya-e-kspertiza.jpg' %}" class="card-img-top" height="160">
                {% elif review.type == 'Компьютерно-Техническая' %}
                <img src="{% static 'images/unnamed_mYzuxqI.jpg' %}" class="card-img-top" height="160">
                {% endif %}
                <div class="card-body">
                  <h4 class="card-title text-center">{{ review.name }}</h4>
                  <h5 class="card-title text-center">{{ review.type }} экспертиза</h5>
                  <p class="card-text">{{ review.review }}</p>
                </div>
              </div>
            </div>
        {% endif %}
      {% empty %}
      <div class="col-md4">
      </div>
      <div class="col-md4">
        <h5 class="text-center text-light">Пока-что отзывов нет...</h5>
      </div>
      <br><br><br><br><br><br><br><br><br><br><br><br>
      {% endfor %}
    </div>
  </div>
  <br>
</div>

<div class="collapse" id="collapseExample">
  <div class="bg-dark">
    <br>
    <div class="container">
      <div class="row">
        {% for review in object_list %}
          {% if forloop.counter <= 3 %}
            <div class="col-md-4">
              <div class="card">
                {% if review.type == 'Строительно-Техническая' %}
                <img src="{% static 'images/Stroitel-no-tehnicheskaya-e-kspertiza.jpg' %}" class="card-img-top" height="160">
                {% elif review.type == 'Компьютерно-Техническая' %}
                <img src="{% static 'images/unnamed_mYzuxqI.jpg' %}" class="card-img-top" height="160">
                {% endif %}
                <div class="card-body">
                  <h4 class="card-title text-center">{{ review.name }}</h4>
                  <h5 class="card-title text-center">{{ review.type }} экспертиза</h5>
                  <p class="card-text">{{ review.review }}</p>
                </div>
              </div>
            </div>
        {% endif %}
      {% empty %}
        {% endfor %}
      </div>
    </div>
    <br>
  </div>
</div>



<!-- Добавить когда будет 6 отзывов
<div class="bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <div class="text-center">
          <button class="btn btn-link" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"><h7 class="text-center">Еще</h7></button>
        </div>
      </div>
    </div>
  </div>
  <br>
</div>
-->

<!-- Остальное -->
<div class="container">
  <br>
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <div class="text-center">
        <h7>Все отзывы модерируются</h7>
      </div>
    </div>
  </div>
</div>



<div class="container">
  <br>
  <a href="/review/" class="btn btn-block btn-outline-dark">Оставить отзыв</a>
</div>

<br>
<br>

<div class="container" id="mainContent">
  <div class="row">
    <div class="col-md-12">
        <h2 class="text-center">ПРОВЕДЕНИЕ СУДЕБНОЙ ЭКСПЕРТИЗЫ</h2>
        <br>
        <ul id="mylist" type="None">
          <li><h5>Судебная экспертиза в ООО "Бюро независимых судебных экспертиз" - это профессиональное экспертное,</h5></li>
          <li><h5>экспертных услуг в самых различных отраслях деятельности. Наши эксперты, специалисты, кадастровые</h5></li>
          <li><h5>оценочное и землеустроительное учреждение, предлагающая своим заказчикам и клиентам полный спектр</h5></li>
          <li><h5>инженеры и юристы имеют большой практический опыт в проведении исследовательских,</h5></li>
          <li><h5>экспериментальных, землеустроительных и кадастровых работ. Использование новейшего оборудования,</h5></li>
          <li><h5>приборов и программных продуктов значительно повышает эффективность работы экспертов и специалистов.</h5></li>
          <li><h5>Профессиональный подход, независимость, объективность и следование самым строгим стандартам - залог</h5></li>
          <li><h5>высокого качества и безупречности наших экспертных заключений и выполненных работ.</h5></li>
          <br>
          <hr>
        </ul>
        <h2 class="text-center">ЭКСПЕРТИЗА В КРАСНОДАРЕ И КРАСНОДАРСКОМ КРАЕ</h2>
        <br>
        <ul id="mylist" type="None">
          <li><h5>Экспертная организация проводит экспертизы и оценочные мероприятия не только на территории</h5></li>
          <li><h5>Краснодарского края, а так же на всей территории Российской Федерации и Республики Крым. Уточнить</h5></li>
          <li><h5>географию нашего обслуживания Вы всегда можете по любому из указанных телефонов.</h5></li>
          <br>
          <li><h5>Экспертное учреждение оказывает услуги по проведению внесудебных исследований по обращению граждан,</h5></li>
          <li><h5>в области строительно-технических экспертиз - технические заключения на соответствие требованиям</h5></li>
          <li><h5>Строительных норм и правил, перепланировок и вновь возведенных строений, пригодности для постоянного</h5></li>
          <li><h5>проживания, определения порядка пользования земельным участком и помещениями, раздела жилого дома,</h5></li>
          <li><h5>обследование не несущих и несущих конструкций. В области оценочных исследований - оценка имущества,</h5></li>
          <li><h5>бизнеса, автотранспортных средств, ущерба. В области почерковедческих экспертиз - технико-</h5></li>
          <li><h5>криминалистическая экспертиза документа, экспертиза почерка. Подробную информацию о возможности</h5></li>
          <li><h5>проведения того или иного экспертного исследования можно уточнить связавшись со специалистами Бюро.</h5></li>
          <br>
          <hr>
        </ul>
        <h2 class="text-center">НЕЗАВИСИМАЯ ЭКСПЕРТНАЯ ОРГАНИЗАЦИЯ.</h2>
        <br>
        <ul id="mylist" type="None">
          <li><h5>В соответствии со ст. 41 федерального закона от 31.05.2001г. №73-ФЗ «О государственной судебно-экспертной</h5></li>
          <li><h5>деятельности в Российской Федерации», судебные экспертизы могут проводить не только государственные</h5></li>
          <li><h5>экспертные учреждения, но и негосударственные экспертные организации, заключения которых имеют</h5></li>
          <li><h5>равную юридическую силу. Преимуществом последних является ускоренное время проведения экспертизы и</h5></li>
          <li><h5>ее стоимость.</h5></li>
          <br>
          <li><h5>Подробнее узнать цены на экспертные услуги Вы можете в разделе <a href="/services">Экспертизы</a></h5></li>
          <li><h5></h5></li>
          <li><h5></h5></li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>

<script>
    var isScrolling = false;

    window.addEventListener("scroll", throttleScroll, false);

    function throttleScroll(e) {
      if (isScrolling == false) {
        window.requestAnimationFrame(function() {
          scrolling(e);
          isScrolling = false;
        });
      }
      isScrolling = true;
    }

    document.addEventListener("DOMContentLoaded", scrolling, false);

    var listItems = document.querySelectorAll("#mainContent ul li");

    function scrolling(e) {


      for (var i = 0; i < listItems.length; i++) {
        var listItem = listItems[i];

        if (isPartiallyVisible(listItem)) {
          listItem.classList.add("active");
        } else {
          listItem.classList.remove("active");
        }
      }
    }

    function isPartiallyVisible(el) {
      var elementBoundary = el.getBoundingClientRect();

      var top = elementBoundary.top;
      var bottom = elementBoundary.bottom;
      var height = elementBoundary.height;

      return ((top + height >= 0) && (height + window.innerHeight >= bottom));
    }

    function isFullyVisible(el) {
      var elementBoundary = el.getBoundingClientRect();

      var top = elementBoundary.top;
      var bottom = elementBoundary.bottom;


    }
</script>



{% endblock %}

BNC/index/templates/index/review.html
{% extends 'index/template.html' %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        {% csrf_token %}
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <form action="" method="post">
                <br>
            <h7 class="text-right">Ваше Ф.И</h7>
                {% csrf_token %}
            <p><input class="form-control form-control-sm" type="text" name="name" maxlength="30" required="" id="id_name"></p>
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <h7 class="text-right">Тип вашей экспертизы</h7>
            {% csrf_token %}
            <select class="form-control form-control-sm" type="text" name="type" maxlength="50" required="" id="id_type" value="">
                <option>Строительно-Техническая</option>
                <option>Компьютерно-Техническая</option>
            </select>
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <br>
            <h7 class="text-right">Ваш отзыв</h7>
            {% csrf_token %}
            <textarea class="form-control form-control-sm" name="review" cols="40" rows="10" required="" id="id_review" style="height: 15em;"></textarea>
        </div>
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <br>
                <a class="btn btn-light" onclick="javascript:history.back(); return false;">Назад</a>
                <input class="btn btn-light" type="submit" id="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" value="Отправить">
            </div>
            </form>
        </div>
    <br>
    <div class="collapse" id="collapseExample">
        <div class="alert alert-primary" role="alert">
      Ваш отзыв отправлен
        </div>
    </div>
    </div>
</div>


{% endblock %}

BNC/index/templates/index/template.html
<!DOCTYPE html>
<html lang="en">
<html>
    <head>
        {% load static %}
        <title>Бюро независимых судебных экспертиз</title>
        <link rel="shortcut icon" href="{% static '/images/logo.ico' %}" type="image/x-icon">
        <link rel="stylesheet" href="{% static 'Bootstrap/css/bootstrap.min.css' %}" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">
    </head>
    <body class="">
        <!-- Bootstrap -->
        <nav class="navbar navbar-light bg-light ">
            <div class="container ">
                <!-- Навбар -->
                    <div class="col-md-3">
                        <a class="navbar-brand" href="/"><img src="{% static 'images/logo2.png' %}" width="275" height="80"></a><!-- Тут должен быть логотип -->
                    </div>
                    <div class="col-md-1">
                        <a href="/services">Экспертизы</a>
                    </div>
                    <div class="col-md-1">
                        <a href="/work"><h7 class="text-right">Вакансии</h7></a>
                    </div>
                    <div class="col-md-1">
                        <a href="/experts">Эксперты</a>
                    </div>
                    <div class="col-md-1">
                        <a href="/contacts">Контакты</a>
                    </div>
                    <div class="col-md-1">
                        <a href="/about">О нас</a>
                    </div>
                    <div class="col-md-3">
                        <h5 class="text-right"><img src="{% static 'images/phone.png' %}" width="35" height="35"> 8 (918) 432 80 70</h5><span></span>
                    </div>
            </div>
            <br>
        </nav>
        {% block content %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="{% static 'Bootstrap\js\bootstrap.js' %}"></script>


        <br>
        <footer class="">
            <p class="bg-light"></p>
            <h6 class="text-center">©2011-2020. ООО "Бюро независимых судебных экспертиз"</h6>
            <p></p>
        </footer>
    </body>
</html>

BNC/index/templates/index/work.html
{% extends 'index/template.html' %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <br><br>
            <h2 class="text-center">Вакансии</h2>
            <br><br>
                        <p>Вакансия Эксперт-товаровед:</p>

            <p>В ООО «Бюро независимых судебных экспертиз» приглашается эксперт-автотехник.</p>

            <p>Профессиональные требования:</p>

            <p>- Высшее образование.</p>

            <p>- Возраст от 23-х лет.</p>

            <p>- Опыт работы в экспертной деятельности от 2-х лет.</p>

            <p>- Наличие навыков оформления судебных (внесудебных) экспертиз.</p>

            <p>Условия:</p>

            <p>- Официальное оформление по договору</p>

            <p>- Заработная плата обсуждается на собеседовании.</p>

            <p>- Работа по совместительству (частичная занятость).</p>

            <p>- Испытательный срок 1 месяц.</p>

            <p>Функциональные обязанности:</p>

            <p>- Проведение товароведческих экспертиз по поручению судебных и правоохранительных органов.</p>

            <p>На собеседование требуется иметь при себе:</p>

            <p>- Развернутое, полноценное резюме в электронном и в распечатанном виде.</p>

            <p>- Распечатку как минимум пяти экспертиз по последнему месту работы.</p>

            <p>- Копию паспорта.Копию трудовой книжки.</p>

        </div>
    </div>
</div>

{% endblock %}